In [ ]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the datasets

datasets = pd.read_csv('adds.csv')
X = datasets.iloc[:, [2,3]].values
Y = datasets.iloc[:, 4].values


In [ ]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

# Decision Tree Classifier

In [ ]:
# Fitting the classifier into the Training set
from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 13)
classifier1.fit(X_Train,Y_Train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=13, splitter='best')

In [ ]:
Y_Pred = classifier1.predict(X_Test)
print(Y_Pred)
print(" \n The accuracy of the model is=", classifier1.score(X_Test,Y_Test)*100,"%")

[0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1
 0 0 0 0 1 1]
 
 The accuracy of the model is= 90.0 %


In [ ]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[53,  5],
       [ 3, 19]])

# Random Forest

In [ ]:
# Fitting the classifier into the Training set
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier(max_depth=7, random_state=13)
classifier2.fit(X_Train,Y_Train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=7, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=13, verbose=0,
                       warm_start=False)

In [ ]:
Y_Pred = classifier2.predict(X_Test)
print(Y_Pred)
print(" \n The accuracy of the model is=", classifier2.score(X_Test,Y_Test)*100,"%")

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1
 0 0 0 0 1 1]
 
 The accuracy of the model is= 96.25 %


In [ ]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[56,  2],
       [ 1, 21]])

# Naive Bayes

In [ ]:
# Fitting the classifier into the Training set
from sklearn.naive_bayes import GaussianNB
classifier3 = GaussianNB()
classifier3.fit(X_Train,Y_Train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
Y_Pred = classifier3.predict(X_Test)
print(Y_Pred)
print(" \n The accuracy of the model is=", classifier3.score(X_Test,Y_Test)*100,"%")

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 1]
 
 The accuracy of the model is= 91.25 %


In [ ]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[55,  3],
       [ 4, 18]])

# Support Vector Machine

In [ ]:
# Fitting the classifier into the Training set
from sklearn import svm
classifier4 =svm.SVC()
classifier4.fit(X_Train,Y_Train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
Y_Pred = classifier4.predict(X_Test)
print(Y_Pred)
print(" \n The accuracy of the model is=", classifier4.score(X_Test,Y_Test)*100,"%")

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]
 
 The accuracy of the model is= 95.0 %


In [ ]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[55,  3],
       [ 1, 21]])

# Hyperparameter Tuning of Decision Tree Classifier

In [ ]:
# Import libraries
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn import decomposition
from sklearn.preprocessing import StandardScaler

In [ ]:
# # Create an scaler object
sc = StandardScaler()

# Create a pca object
pca = decomposition.PCA()

In [ ]:
 pipe = Pipeline(steps=[('sc', sc),
                           ('pca', pca),
                           ('decisiontree', classifier1)])

In [ ]:
n_components = list(range(1,X.shape[1]+1,1))
# parameters of decision tree classifier
criterion = ['gini', 'entropy']
max_depth = [4,6,8,12]


In [ ]:
  parameters = dict(pca__n_components=n_components,
                      decisiontree__criterion=criterion,
                      decisiontree__max_depth=max_depth)

In [ ]:
clf = GridSearchCV(pipe, parameters,verbose=1)


In [ ]:
clf.fit(X_Train, Y_Train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    0.3s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('sc',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('pca',
                                        PCA(copy=True, iterated_power='auto',
                                            n_components=None,
                                            random_state=None,
                                            svd_solver='auto', tol=0.0,
                                            whiten=False)),
                                       ('decisiontree',
                                        DecisionTreeClassifier(ccp_alpha=0.0,
                                                               class_weight=None,
                                                              

In [ ]:
print('Best Criterion:', clf.best_estimator_.get_params()['decisiontree__criterion'])
print('Best max_depth:', clf.best_estimator_.get_params()['decisiontree__max_depth'])
print('Best Number Of Components:', clf.best_estimator_.get_params()['pca__n_components'])
print(); print(clf.best_estimator_.get_params()['decisiontree'])

Best Criterion: entropy
Best max_depth: 4
Best Number Of Components: 2

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=13, splitter='best')


In [ ]:
optimized_decision_tree=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=13, splitter='best')

In [ ]:
optimized_decision_tree.fit(X_Train,Y_Train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=13, splitter='best')

# Performance Change Evaluation
### After Optimization Score = 95%
### Before Optimization Score = 90%

In [ ]:
optimized_decision_tree.score(X_Test,Y_Test)

0.95

##### Similarly Hyperparameter Tuning Can be applied for all other classifiers to take them to their best performance